### ISSUE TITLE
Error when install HybridChenck form githup

### ISSUE THREAD

**Issue by yexiaying** [BenJWard/HybridCheck#28]
I installed HybridCheck failed from githup. The error messages are as follows:
![image](https://user-images.githubusercontent.com/20267631/71072895-5ad89b00-21ba-11ea-910a-724acba1fc96.png)
You mentioned a windows GUI version can be get from HybridCheck website in your supporting file Appendix S2, but I can not find it. where can I get this version.

**Comment by BenJWard** [comment]
Do you have Biostrings, and IRanges installed from BioConductor? They are required for HybridCheck to work.

I've been looking for a while for a solution to the problem of Bioconductor dependencies, since they have their own little system for installing and managing packages.

I think there is a solution. If instead of using `devtools::install_github`, you use `remotes::install_github` to install HybridCheck, it should make sure you have all the dependencies, including the Bioconductor ones.

Try
 
```R
install.packages("remotes")
library(remotes)
remotes::install_github("BenJWard/HybridCheck", build_vignettes = T)
```

See if that works. If not it means the vignette is not building for some other reason we'll have to figure out.

**Comment by yexiaying** [comment]
I tried the way you mentioned but failed. I have install the Biostrings and IRanges from BioConductor, and I can load these packages sucessfully in my Rstudio. But it still showed that these two packages not available when install the HybridCheck package. the R version I used is 3.6.2.
![image](https://user-images.githubusercontent.com/20267631/71238429-fe52b880-233e-11ea-8faa-b9584185b0ae.png)

**Comment by BenJWard** [comment]
@yexiaying Ok this is what I could expect to see on my machine:

**Comment by yexiaying** [comment]
I tried remotes::install_github("BenJWard/HybridCheck", build_vignettes = F) and it worked. Thank you very much!

**Comment by BenJWard** [comment]
Great! If you need to build the manual, try ensuring knitr is installed first.
